<?php

namespace Simple\ProfileBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * cityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class cityRepository extends EntityRepository
{
    
    public function getCitiesByState($id) {
//SQL       
//SELECT * FROM city JOIN state ON city.state_id = state.id
//ó
//SELECT t.id FROM persona JOIN titular AS t ON persona.titular_id = t.id WHERE persona.ci = {ci}        
        $em = $this->getEntityManager();
        
        $qb = $em->createQueryBuilder();  
        
        $qb->select('c')->from('SimpleProfileBundle:City', 'c')->join('c.state', 's')
                ->where('s.id=:id')->setParameter('id', $id);
        
        $result = $qb->getQuery()->getResult();
        return $result;//$result[0]['id'];//$result[0]->getId();
    }      
}
