<?php

namespace Simple\ProfileBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * stateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class stateRepository extends EntityRepository
{
}
